## Import Numpy package

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress = True ,linewidth= 100, precision = 2)

## Importing the Data

In [3]:
loan_data = np.genfromtxt("loan-data.csv", delimiter=";", skip_header=1, autostrip=1)
loan_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Examine missing elements

In [4]:
#there are many cells which do not have numeric data
np.isnan(loan_data).sum()

88005

In [5]:
temporary_fill = np.nanmax(loan_data) + 1 
## the above is greater than any actual value from the data set, so it will serve as a filler for missing data

temporary_mean = np.nanmean(loan_data, axis=0)  #store mean of each column
temporary_mean

<ipython-input-5-0fe47d277eb0>:4: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(loan_data, axis=0)  #store mean of each column


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [6]:
#col 2,4,6,9,10,11,12,13 are strings


In [7]:
# store min , max and mean data which will be used later
temporary_stats = np.array([np.nanmin(loan_data, axis = 0), temporary_mean, np.nanmax(loan_data, axis = 0)])
temporary_stats

<ipython-input-7-19cd666091b1>:2: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(loan_data, axis = 0), temporary_mean, np.nanmax(loan_data, axis = 0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting dataset into numeric and string

### Splitting columns

In [8]:
#identify which columns are strings
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [9]:
#identify which columns are numeric
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Importing the columns of dtype string

In [10]:
loan_data_strings = np.genfromtxt("loan-data.csv", 
                                  delimiter=";", 
                                  skip_header=1, 
                                  usecols=columns_strings, 
                                  autostrip=1, 
                                  dtype= np.str_)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Importing the columns having numeric data

In [11]:
loan_data_numeric = np.genfromtxt("loan-data.csv", 
                                  delimiter=";", 
                                  skip_header=1, 
                                  usecols=columns_numeric, 
                                  autostrip=1, 
                                  filling_values= temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### Importing header names

In [12]:
header_names = np.genfromtxt("loan-data.csv", 
                                  delimiter=";", 
                                  skip_footer= loan_data.shape[0], 
                                  autostrip=1, 
                                  dtype= np.str_)
header_names

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [13]:
## divide the headers to header_numeric and header_strings
header_strings, header_numeric = header_names[columns_strings], header_names[columns_numeric]

### Finished splitting text and numeric data 

In [14]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_var = np.load(file_name + ".npz")
    return(checkpoint_var)

In [15]:
#the above was a simple checkpoint function

### Manipulating issue date of loan data strings 

In [16]:
#issue date is first column of loan data strings
loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [17]:
#no of unique values
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [18]:
#all months are in year 2015 so we can remove it
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0],"-15")
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [19]:
# since we want to quantify all categorical data, we can convert all month names to the month number
# jan = 1 , feb = 2, ....., dec = 12
months = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [20]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                      i, 
                                      loan_data_strings[:,0])
loan_data_strings[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

### Manipulating Loan status

In [21]:
#determining the type of values in loan status
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [22]:
# to quantify, replace good acc with 1 and bad acc with 0
bad_status = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], bad_status),0,1)
np.unique(loan_data_strings[:,1])


array(['0', '1'], dtype='<U69')

### Manipulating Term

In [23]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [24]:
#we can remove months
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2],' months')
np.unique(loan_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [25]:
# to clarify the unit we change the header to term_months
header_strings[2] = 'term_months' 

In [26]:
# remove blank by assuming the worst i.e. 60 months
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',60,loan_data_strings[:,2])
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

### Manipulating grade and subgrade

In [27]:
#grade
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [28]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [29]:
#since subgrade is grade + number . we can replace a empty subgrade with grade + lowest number(5)
#filling subgrade

for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i), 
                                          i+'5', 
                                          loan_data_strings[:,4])
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [30]:
#there are some more empty subgrades we can replace them with a new subgrade which can be considered as the lowest 'H1'
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == ''),
                                          'H1', 
                                          loan_data_strings[:,4])
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [31]:
#we have all data in subgrade, therefore grade column is redundant. we can remove grade column
loan_data_strings = np.delete(loan_data_strings, obj = 3, axis = 1)
header_strings = np.delete(header_strings, 3)
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [32]:
#convert subgrade to numeric each grade corresponds to a number A1 = 1, A2= 2 and so on
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0]+1))
dict_sub_grade = dict(zip(keys,values))
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [33]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i, 
                                      dict_sub_grade[i],
                                      loan_data_strings[:,3])
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Manipulating Verification Status

In [34]:
header_strings

array(['issue_d', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [35]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [36]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == 'Source Verified') | (loan_data_strings[:,4] == 'Verified')  
                                    , 1,
                                      0)

np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

### Manipulating URL column

In [37]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [38]:
#all url have the same beginning we can remove it
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [39]:
#it looks like the ID lets compare to chk if it is true
np.array_equal(loan_data_strings[:,5].astype(dtype = np.int32),loan_data_numeric[:,0].astype(dtype = np.int32))

True

In [40]:
#hence we can remove the url column since it contains no useful information
loan_data_strings = np.delete(loan_data_strings, obj = 5, axis =1)
header_strings = np.delete(header_strings, obj = 5)
loan_data_strings

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [41]:
header_strings

array(['issue_d', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

### Address state

In [42]:
states_name,states_count = np.unique(loan_data_strings[:,5], return_counts = True)

In [43]:
np.unique(loan_data_strings[:,5]).size

50

In [44]:
sorted_index_state = np.argsort(-states_count)
states_name[sorted_index_state] , states_count[sorted_index_state]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [45]:
#many values are unrepresented by any state so we can group these states in a different manner a geographical location wise
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])



In [46]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '', 
                                  0, 
                                  loan_data_strings[:,5])
np.unique(loan_data_strings[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [47]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_east), 4, loan_data_strings[:,5])
np.unique(loan_data_strings[:,5])
                                  

array(['0', '1', '2', '3', '4'], dtype='<U69')

### Changing loan_data_strings to numeric.
The array consists of numbers but of dtype string</b>

In [48]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [49]:
loan_data_strings = loan_data_strings.astype(dtype = np.int32)

In [50]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [51]:
#create a checkpoint 
checkpoint_strings = checkpoint("checkpoint-strings", header_strings, loan_data_strings)
np.array_equal(loan_data_strings,checkpoint_strings["data"])

True

In [52]:
#saved a file in npz format that has the string data 

## Numeric Data 

In [53]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [54]:
np.isnan(loan_data_numeric).sum()
#no NAN present

0

In [55]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Checking ID column

In [56]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()
# 0 mean we didnt fill it yet

0

### Temporary Statistics

In [57]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [58]:
temporary_stats[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

### Funded Amount 

In [59]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [60]:
# replace temporary fill with the minimum 
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill, 
                                  temporary_stats[0,columns_numeric[2]], 
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### Change temporary fill of other variables to max value of that column

In [61]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [62]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill, 
                                  temporary_stats[2,columns_numeric[i]], 
                                  loan_data_numeric[:,i])
loan_data_numeric #changes are made 

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Convert currency to euro

In [63]:
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter= ',', autostrip = True, skip_header=True, usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [64]:
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [65]:
exchange_rate = loan_data_strings[:,0]
exchange_rate

array([ 5,  0,  9, ...,  6,  4, 12])

In [66]:
# new column for exchange_rate having closing exchange month wise

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)    

# for month not specified exchange rate is mean of all closing exchange rate for each month
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [67]:
exchange_rate = exchange_rate.reshape((10000,1))
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [68]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [69]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [70]:
header_numeric = np.concatenate((header_numeric, np.array(['Exchange_Rate'])))

In [71]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_Rate'],
      dtype='<U19')

### Currency Exchange

In [72]:
header_numeric[6]

'Exchange_Rate'

In [73]:
# Determine the columns having monetary data in USD
column_dollar =np.array([1,2,4,5])
loan_data_numeric[:,column_dollar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [74]:
# stack monetary data in euro to the loan_data_numeric dataset
for i in column_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6], (10000,1))))

In [75]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [76]:
loan_data_numeric.shape

(10000, 11)

In [77]:
#add headers for the new columns

header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[column_dollar]])
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [78]:
header_numeric = np.concatenate((header_numeric,header_additional))

In [79]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_Rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [80]:
header_numeric[column_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[column_dollar]])
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'Exchange_Rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [81]:
column_index = [0,1,7,2,8,3,4,9,5,10,6]
header_numeric = header_numeric[column_index]

In [82]:
loan_data_numeric = loan_data_numeric[:,column_index]

### Interest Rate

In [83]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [84]:
#tranform interest rates from percentage to actual value

loan_data_numeric[:,5]/=100
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Numeric Checkpoint

In [85]:
Checkpoint_Numeric = checkpoint("Checkpoint-Numeric", header_numeric, loan_data_numeric)

In [86]:
Checkpoint_Numeric['header'],Checkpoint_Numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'Exchange_Rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

### Completing Dataset

In [87]:
# stacking numeric and string dataset to form final dataset values
loan_final_data = np.hstack((Checkpoint_Numeric['data'],checkpoint_strings['data']))

In [88]:
loan_final_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [89]:
header_final = np.concatenate((Checkpoint_Numeric['header'],checkpoint_strings['header']))

In [90]:
# Ordering data set by ID 
loan_final_data = loan_final_data[np.argsort(loan_final_data[:,0])]
loan_final_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [91]:
# Stacking header row on top of final dataset
loan_final_data = np.vstack((header_final,loan_final_data))
loan_final_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [92]:
np.savetxt("loan-data-preprocessed.csv", loan_final_data, fmt = '%s', delimiter = ',')

### New File Saved
### Data Preprocessing completed